<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/radi/public_html/countries-agavi/app/modules/Countries/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2017-02-14T09:29:46+0000

return array (
  'countriesCountriesBaseAction' => '/home/radi/public_html/countries-agavi/app/modules/Countries/lib/action/countriesCountriesBaseAction.class.php',
  'countriesCountriesBaseModel' => '/home/radi/public_html/countries-agavi/app/modules/Countries/lib/model/countriesCountriesBaseModel.class.php',
  'countriesCountriesBaseView' => '/home/radi/public_html/countries-agavi/app/modules/Countries/lib/view/countriesCountriesBaseView.class.php',
);

?>