<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/radi/public_html/countries-agavi/app/modules/Countries/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2017-02-14T09:29:46+0000

return array (
)

?>