<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/radi/public_html/countries-agavi/app/config/databases.xml
// Generated by: AgaviDatabaseConfigHandler
// Date: 2017-02-14T09:29:45+0000

$database = new AgaviPdoDatabase();
$this->databases['pdo_mysql_main'] = $database;
$database->initialize($this, array (
  'dsn' => 'mysql:host=localhost;dbname=countries',
  'username' => 'root',
  'password' => 'masterkey',
));
$this->defaultDatabaseName = 'pdo_mysql_main';

?>