<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/radi/public_html/countries-agavi/app/modules/Countries/validate/ListCountries.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2017-02-14T09:29:46+0000



?>