<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/radi/public_html/countries-agavi/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2017-02-14T09:29:43+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'Default',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Default',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'Default',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'Default',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Default',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'Default',
  'actions.login_action' => 'Login',
  'core.app_name' => 'countries',
  'core.available' => true,
  'core.debug' => true,
  'core.use_database' => true,
  'core.use_logging' => false,
  'core.use_security' => true,
  'core.use_translation' => false,
  'core.error_messages' => 
  array (
    'country_create' => 'Cannot create country. Already exists???',
  ),
  'exception.default_template' => '/usr/share/php/agavi/exception/templates/shiny.php',
  'exception.templates.console' => '/usr/share/php/agavi/exception/templates/plaintext.php',
));

?>